SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[sys_settings] (
    [key]   VARCHAR (100)  NOT NULL,
    [value] NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_sys_settings] PRIMARY KEY CLUSTERED ([key] ASC)
);
