name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  publish-linux-arm64:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Publish linux arm64
        run: dotnet publish --arch arm64 --os linux --configuration Release -o /tmp/publish/linux-arm64 ./src/Server/Server.csproj
      - name: Tar linux arm64
        run: tar -cvf /tmp/publish/linux-arm64.tar /tmp/publish/linux-arm64
      - name: Upload linux arm64
        uses: actions/upload-artifact@v3
        with:
          name: sqliste-linux-arm64
          path: /tmp/publish/linux-arm64.tar

  publish-linux-x64:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Publish linux x64
        run: dotnet publish --arch x64 --os linux --configuration Release -o /tmp/publish/linux-x64 ./src/Server/Server.csproj
      - name: Tar linux x64
        run: tar -cvf /tmp/publish/linux-x64.tar /tmp/publish/linux-x64
      - name: Upload linux x64
        uses: actions/upload-artifact@v3
        with:
          name: sqliste-linux-x64
          path: /tmp/publish/linux-x64.tar

  publish-win-arm64:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Publish Windows arm64
        run: dotnet publish --arch arm64 --os win --configuration Release -o /tmp/publish/win-arm64 ./src/Server/Server.csproj
      - name: Upload Windows arm64
        uses: actions/upload-artifact@v3
        with:
          name: sqliste-win-arm64
          path: /tmp/publish/win-arm64

  publish-win-x64:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Publish Windows x64
        run: dotnet publish --arch x64 --os win --configuration Release -o /tmp/publish/win-x64 ./src/Server/Server.csproj
      - name: Upload Windows x64
        uses: actions/upload-artifact@v3
        with:
          name: sqliste-win-x64
          path: /tmp/publish/win-x64
